# Generated by Django 6.0.5 on 2026-05-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('composition', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('drops', 'Drops'), ('cream', 'Cream'), ('others', 'Others')], default='tablet', max_length=20)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('rack_number', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(blank=True, max_length=20)),
                ('shelf', models.CharField(blank=True, max_length=20)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('min_stock', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='drugs.drug')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
