# Generated by Django 6.0.5 on 2026-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date'], 'verbose_name_plural': 'Batches'},
        ),
    ]
