# Generated by Django 6.0.5 on 2026-05-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_remove_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
    ]
